# Generated by Django 5.1.15 on 2026-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='browser_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interview',
            name='calendar_event_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='interviewer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='meeting_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
