# Generated by Django 5.1.15 on 2026-06-26 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('job_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_reminder_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company_notes', models.TextField(blank=True)),
                ('resume_summary', models.TextField(blank=True)),
                ('skills_to_improve', models.TextField(blank=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('skill_gap_analysis', models.TextField(blank=True)),
                ('ai_interview_questions', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
