# Generated by Django 5.1.15 on 2026-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='salary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
