# Generated by Django 5.1.15 on 2026-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
